inherit_from:
  - https://raw.githubusercontent.com/carbonfive/c5-conventions/master/rubocop/rubocop.yml

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - "tmp/**/*"
    - "vendor/bundle/**/*"

Rails:
  Enabled: false
Metrics/LineLength:
  Exclude:
    - "spec/**/*"
